### PR TITLE
CodeCov settings should be modified to reduce target coverage (100% -> 70%).

### PR DESCRIPTION
**Pull request by skonmeme**

### CODE REVIEW

**Comment by sangjohan** [comment]
What is "CodeCode Setting" like? and What does "Target Coverage" mean?

**Comment by skonmeme** [comment]
FYI
* [CodeCov YML](https://docs.codecov.io/docs/codecov-delta)
* [codecov.yml](https://github.com/sktivd/collabExample/blob/feature-codecov/codecov.yml) in collabExample

**Comment by sangjohan** [comment]
So you intend to merge some branch into master if the branch has more than 70% difference compared with master. It seems to be less strict policy. Am I understood correctly?

**Comment by skonmeme** [comment]
It does not mean code diff.

See check list below. There are 4 types of tests, in which three test exist related to codecov. It is hard to expect very high target coverage on whole codes as projects are growing up (for especially open projects). However, default requires 100% and shows fail messages. It is impossible target to achieve.
I suggests less strict target (70%). Might be reasonable.

**Comment by sangjohan** [comment]
I want to ask you basic question...what is "target coverage"?...more basic question... what is "target"?

**Pull request merged**
